Made createMediaStore a named import (#1040)
I'm having the same problem, as the described in
[this](https://github.com/muxinc/media-chrome/issues/886) issue.

The error I receive:
```
media-controller.js:440 Uncaught TypeError: (0 , import_media_store.default) is not a function
    at MediaController.setupDefaultStore_fn (media-controller.js:440:1)
    at MediaController.connectedCallback (media-controller.js:219:1)
```

Which shows me, that the problem is here:
`var import_media_store =
__toESM(require("./media-store/media-store.js"), 1);`

By making **createMediaStore** a named export, and using that, this
problem disappears, and the video player works perfectly.

---------

Co-authored-by: Tibor Szenasi <tibor.szenasi@accretivetg.com>